# Generated by Django 4.0.4 on 2022-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_mon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoderado',
            old_name='p_Apellido',
            new_name='p_apellido',
        ),
        migrations.RenameField(
            model_name='apoderado',
            old_name='s_Apellido',
            new_name='s_apellido',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=16, verbose_name='Clave del Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='Correo del Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=11, verbose_name='Rut del usuario'),
        ),
    ]
