# Generated by Django 4.0.4 on 2022-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_mon', '0002_rename_p_apellido_apoderado_p_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='tiempo_exp_lab',
            field=models.CharField(max_length=100, verbose_name='Experiencias del cuidador'),
        ),
    ]
