# Generated by Django 4.0.4 on 2022-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_mon', '0003_alter_cuidador_tiempo_exp_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direc_apoderado',
            name='deptoApoderado',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Depto del apoderado'),
        ),
        migrations.AlterField(
            model_name='direc_cuidador',
            name='deptoCuidador',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Depto del cuidador'),
        ),
    ]
