# Generated by Django 4.0.4 on 2022-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_mon', '0004_alter_direc_apoderado_deptoapoderado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción de parte de la cuidadora'),
        ),
    ]
