# Generated by Django 4.0.4 on 2022-06-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_mon', '0006_alter_bloque_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calificaciones'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='comentario',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentarios'),
        ),
    ]
