# Generated by Django 4.0.4 on 2022-06-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_mon', '0007_alter_servicio_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='emoji',
            field=models.IntegerField(blank=True, null=True, verbose_name='emojis'),
        ),
    ]
