# Generated by Django 4.0.4 on 2022-06-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go_mon', '0008_alter_servicio_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='emoji',
        ),
    ]
