from django.contrib import admin
from django.urls import path, include
from .views import Historial_evaluacion, Pag_Principal, defrecerva, elimHijo, habilidades, ingresaidioma, mapa, modiA, modiMenor, modif, modifApo, modificar_cuidador, modificarCui,salir,registrar_menor,inicio_sesion, listarroles,iniciouser,adm,admbanear,admministrador,buscador,cambio,registrar_apoderado, registrar_cuidador, registrar_dir, registrar_dircui, registro, servicui, volapo, volcui

urlpatterns = [
    path('',Pag_Principal,name="Pag_Principal"),
    path('perfil/', inicio_sesion, name="perfil"),
    path('iniciouser/', iniciouser, name="iniciouser"),
    path('adm/', adm, name="adm"),
    path('Historial_evaluacion/', Historial_evaluacion ,name ="Historial_evaluacion"),
    path('admbanear/', admbanear, name="admbanear"),
    path('admministrador/', admministrador, name="admministrador"),
    path('cambio/', cambio, name ="cambio"),
    path('mod_perfil/<rut>', modificar_cuidador, name="mod_perfil"),
    path('modificarCui', modificarCui, name="modificarCui"),
    path('volcui/<rut>',volcui, name="volcui"),
    path('registro/', listarroles, name="registro"),
    path('reg/', registro, name="reg"),
    path('registro_apo/', registro, name="registro_apo"),
    path('reg_apoderado/', registrar_apoderado, name="reg_apoderado"),
    path('direccion_apo/', registrar_apoderado, name="direccion_apo"),
    path('dir_apo/',registrar_dir,name="dir_apo"),
    path('registro_cui/', registro, name="registro_cui"),
    path('reg_cuidador/', registrar_cuidador, name="reg_cuidador"),
    path('direccion_cui/', registrar_cuidador, name="direccion_cui"),
    path('mapa/<rut>/<rutap>', mapa, name ="mapa"),
    path('defrecerva/<rut>/<rutap>', defrecerva, name ="defrecerva"),
    path('servicui/<rut>/<rutap>', servicui, name ="servicui"),
    path('dir_cui/', registrar_dircui, name="dir_cui"),
    path('descripcion/', registrar_dircui, name="descripcion"),
    path('cui_idioma/', ingresaidioma, name="cui_idioma"),
    path('reg_menor/',registrar_menor,name="reg_menor"),
    path('salir/', salir, name ="salir"),
    path('descrip/', habilidades, name="descrip"),
    path('eliminar/<id>/<rut>',elimHijo, name="eliminar_hijo"),
    path('modiMenor/<id>/<rut>',modiMenor, name="modiMenor"),
    path('modif/<id>/<rut>',modif, name="modif"),
    path('volapo/<rut>',volapo, name="volapo"),
    path('modifApo/<rut>',modifApo, name="modifApo"),
    path('modiA/<rut>',modiA, name="modiA"),
]
